name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your suggestion! Please check existing [issues](https://github.com/Finrandojin/alexandria-audiobook/issues) to avoid duplicates.

  - type: textarea
    id: description
    attributes:
      label: What would you like to see?
      description: A clear description of the feature or improvement.
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Use case
      description: Why is this useful? What problem does it solve?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Have you tried any workarounds or alternative approaches?
    validations:
      required: false
